<select data-placeholder="<?php _e('Find by Country or State...', 'anatol'); ?>" id="inputCountry" class="chosen-select form-control" tabindex="-1" name="country" required>
  <option value="" disabled selected ><?php _e('Find by Country or State...') ?></option>
  <optgroup label="North America">
    <option value="CA">Canada</option>
    <option value="GL">Greenland</option>
    <option value="MX">Mexico</option>
  </optgroup>
  <optgroup label="United States">
    <option value="US-AL">Alabama</option>
    <option value="US-AK">Alaska</option>
    <option value="US-AZ">Arizona</option>
    <option value="US-AR">Arkansas</option>
    <option value="US-CA">California</option>
    <option value="US-CO">Colorado</option>
    <option value="US-CT">Connecticut</option>
    <option value="US-DE">Delaware</option>
    <option value="US-DC">District of Columbia</option>
    <option value="US-FL">Florida</option>
    <option value="US-GA">Georgia</option>
    <option value="US-HI">Hawaii</option>
    <option value="US-ID">Idaho</option>
    <option value="US-IL">Illinois</option>
    <option value="US-IN">Indiana</option>
    <option value="US-IA">Iowa</option>
    <option value="US-KS">Kansas</option>
    <option value="US-KY">Kentucky</option>
    <option value="US-LA">Louisiana</option>
    <option value="US-ME">Maine</option>
    <option value="US-MD">Maryland</option>
    <option value="US-MA">Massachusetts</option>
    <option value="US-MI">Michigan</option>
    <option value="US-MN">Minnesota</option>
    <option value="US-MS">Mississippi</option>
    <option value="US-MO">Missouri</option>
    <option value="US-MT">Montana</option>
    <option value="US-NE">Nebraska</option>
    <option value="US-NV">Nevada</option>
    <option value="US-NH">New Hampshire</option>
    <option value="US-NJ">New Jersey</option>
    <option value="US-NM">New Mexico</option>
    <option value="US-NY">New York</option>
    <option value="US-NC">North Carolina</option>
    <option value="US-ND">North Dakota</option>
    <option value="US-OH">Ohio</option>
    <option value="US-OK">Oklahoma</option>
    <option value="US-OR">Oregon</option>
    <option value="US-PA">Pennsylvania</option>
    <option value="US-RI">Rhode Island</option>
    <option value="US-SC">South Carolina</option>
    <option value="US-SD">South Dakota</option>
    <option value="US-TN">Tennessee</option>
    <option value="US-TX">Texas</option>
    <option value="US-UT">Utah</option>
    <option value="US-VT">Vermont</option>
    <option value="US-VA">Virginia</option>
    <option value="US-WA">Washington</option>
    <option value="US-WV">West Virginia</option>
    <option value="US-WI">Wisconsin</option>
    <option value="US-WY">Wyoming</option>
  </optgroup>
  <optgroup label="Europe">
    <option value="AX">Aland</option>
    <option value="AL">Albania</option>
    <option value="AD">Andorra</option>
    <option value="AT">Austria</option>
    <option value="BY">Belarus</option>
    <option value="BE">Belgium</option>
    <option value="BA">Bosnia and Herz.</option>
    <option value="BG">Bulgaria</option>
    <option value="HR">Croatia</option>
    <option value="CZ">Czech Rep.</option>
    <option value="DK">Denmark</option>
    <option value="EE">Estonia</option>
    <option value="FO">Faeroe Is.</option>
    <option value="FI">Finland</option>
    <option value="FR">France</option>
    <option value="DE">Germany</option>
    <option value="GR">Greece</option>
    <option value="GG">Guernsey</option>
    <option value="HU">Hungary</option>
    <option value="IS">Iceland</option>
    <option value="IM">Isle of Man</option>
    <option value="IT">Italy</option>
    <option value="JE">Jersey</option>
    <option value="XK">Kosovo</option>
    <option value="LV">Latvia</option>
    <option value="LI">Liechtenstein</option>
    <option value="LT">Lithuania</option>
    <option value="LU">Luxembourg</option>
    <option value="MK">Macedonia</option>
    <option value="MT">Malta</option>
    <option value="MD">Moldova</option>
    <option value="ME">Montenegro</option>
    <option value="NL">Netherlands</option>
    <option value="NO">Norway</option>
    <option value="PL">Poland</option>
    <option value="PT">Portugal</option>
    <option value="RO">Romania</option>
    <option value="RU">Russia</option>
    <option value="SM">San Marino</option>
    <option value="RS">Serbia</option>
    <option value="SK">Slovakia</option>
    <option value="SI">Slovenia</option>
    <option value="ES">Spain</option>
    <option value="SE">Sweden</option>
    <option value="CH">Switzerland</option>
    <option value="UA">Ukraine</option>
    <option value="GB">United Kingdom</option>
  </optgroup>
  <optgroup label="Caribbean Islands">
    <option value="BS">Bahamas</option>
    <option value="CU">Cuba</option>
    <option value="DM">Dominica</option>
    <option value="DO">Dominican Republic</option>
    <option value="HT">Haiti</option>
    <option value="JM">Jamaica</option>
    <option value="PR">Puerto Rico</option>
    <option value="LC">Saint Lucia</option>
    <option value="TT">Trinidad &amp; Tobago</option>
  </optgroup>
  <optgroup label="South America">
    <option value="AR">Argentina</option>
    <option value="BO">Bolivia</option>
    <option value="BR">Brazil</option>
    <option value="CL">Chile</option>
    <option value="CO">Colombia</option>
    <option value="EC">Ecuador</option>
    <option value="FK">Falkland Is.</option>
    <option value="GY">Guyana</option>
    <option value="PY">Paraguay</option>
    <option value="PE">Peru</option>
    <option value="SR">Suriname</option>
    <option value="UY">Uruguay</option>
    <option value="VE">Venezuela</option>
  </optgroup>
  <optgroup label="Central America">
    <option value="CA-BZ">Belize</option>
    <option value="CA-CR">Costa Rica</option>
    <option value="CA-SV">El Salvador</option>
    <option value="CA-GT">Guatemala</option>
    <option value="CA-HN">Honduras</option>
    <option value="CA-NI">Nicaragua</option>
    <option value="CA-PA">Panama</option>
  </optgroup>
  <optgroup label="Asia">
    <option value="AF">Afghanistan</option>
    <option value="AM">Armenia</option>
    <option value="AZ">Azerbaijan</option>
    <option value="BH">Bahrain</option>
    <option value="BD">Bangladesh</option>
    <option value="BT">Bhutan</option>
    <option value="BN">Brunei</option>
    <option value="KH">Cambodia</option>
    <option value="CN">China</option>
    <option value="CY">Cyprus</option>
    <option value="KP">Dem. Rep. Korea</option>
    <option value="GE">Georgia</option>
    <option value="HK">Hong Kong</option>
    <option value="IN">India</option>
    <option value="ID">Indonesia</option>
    <option value="IR">Iran</option>
    <option value="IQ">Iraq</option>
    <option value="IL">Israel</option>
    <option value="JP">Japan</option>
    <option value="JO">Jordan</option>
    <option value="KZ">Kazakhstan</option>
    <option value="KR">Korea</option>
    <option value="KW">Kuwait</option>
    <option value="KG">Kyrgyzstan</option>
    <option value="LA">Lao PDR</option>
    <option value="LB">Lebanon</option>
    <option value="MY">Malaysia</option>
    <option value="MN">Mongolia</option>
    <option value="MM">Myanmar</option>
    <option value="XC">N. Cyprus</option>
    <option value="NP">Nepal</option>
    <option value="OM">Oman</option>
    <option value="PK">Pakistan</option>
    <option value="PS">Palestine</option>
    <option value="PH">Philippines</option>
    <option value="QA">Qatar</option>
    <option value="SA">Saudi Arabia</option>
    <option value="-99">Siachen Glacier</option>
    <option value="SG">Singapore</option>
    <option value="LK">Sri Lanka</option>
    <option value="SY">Syria</option>
    <option value="TW">Taiwan</option>
    <option value="TJ">Tajikistan</option>
    <option value="TH">Thailand</option>
    <option value="TL">Timor-Leste</option>
    <option value="TR">Turkey</option>
    <option value="TM">Turkmenistan</option>
    <option value="AE">United Arab Emirates</option>
    <option value="UZ">Uzbekistan</option>
    <option value="VN">Vietnam</option>
    <option value="YE">Yemen</option>
  </optgroup>
  <optgroup label="Oceania">
    <option value="AU">Australia</option>
    <option value="FJ">Fiji</option>
    <option value="PF">Fr. Polynesia</option>
    <option value="GU">Guam</option>
    <option value="KI">Kiribati</option>
    <option value="FM">Micronesia</option>
    <option value="NC">New Caledonia</option>
    <option value="NZ">New Zealand</option>
    <option value="NU">Niue</option>
    <option value="PW">Palau</option>
    <option value="PG">Papua New Guinea</option>
    <option value="WS">Samoa</option>
    <option value="SB">Solomon Is.</option>
    <option value="VU">Vanuatu</option>
  </optgroup>
  <optgroup label="Africa">
    <option value="DZ">Algeria</option>
    <option value="AO">Angola</option>
    <option value="BJ">Benin</option>
    <option value="BW">Botswana</option>
    <option value="BF">Burkina Faso</option>
    <option value="BI">Burundi</option>
    <option value="CM">Cameroon</option>
    <option value="CV">Cape Verde</option>
    <option value="CF">Central African Rep.</option>
    <option value="TD">Chad</option>
    <option value="KM">Comoros</option>
    <option value="CG">Congo</option>
    <option value="CI">Côte D’Ivoire</option>
    <option value="CD">Dem. Rep. Congo</option>
    <option value="DJ">Djibouti</option>
    <option value="EG">Egypt</option>
    <option value="GQ">Eq. Guinea</option>
    <option value="ER">Eritrea</option>
    <option value="ET">Ethiopia</option>
    <option value="GA">Gabon</option>
    <option value="GM">Gambia</option>
    <option value="GH">Ghana</option>
    <option value="GN">Guinea</option>
    <option value="GW">Guinea-Bissau</option>
    <option value="KE">Kenya</option>
    <option value="LS">Lesotho</option>
    <option value="LR">Liberia</option>
    <option value="LY">Libya</option>
    <option value="MG">Madagascar</option>
    <option value="MW">Malawi</option>
    <option value="ML">Mali</option>
    <option value="MR">Mauritania</option>
    <option value="MA">Morocco</option>
    <option value="MZ">Mozambique</option>
    <option value="NA">Namibia</option>
    <option value="NE">Niger</option>
    <option value="NG">Nigeria</option>
    <option value="RW">Rwanda</option>
    <option value="SS">S. Sudan</option>
    <option value="ST">São Tomé and Príncipe</option>
    <option value="SN">Senegal</option>
    <option value="SL">Sierra Leone</option>
    <option value="SO">Somalia</option>
    <option value="XS">Somaliland</option>
    <option value="ZA">South Africa</option>
    <option value="SD">Sudan</option>
    <option value="SZ">Swaziland</option>
    <option value="TZ">Tanzania</option>
    <option value="TG">Togo</option>
    <option value="TN">Tunisia</option>
    <option value="UG">Uganda</option>
    <option value="EH">W. Sahara</option>
    <option value="ZM">Zambia</option>
    <option value="ZW">Zimbabwe</option>
  </optgroup>
</select>
